// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ReaperFunction
 */
export interface ReaperFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/image-builders/aws-image-builder/reaper.
 */
export class ReaperFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ReaperFunctionProps) {
    super(scope, id, {
      description: 'src/image-builders/aws-image-builder/reaper.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/image-builders/aws-image-builder/reaper.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}