name: test-examples
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  test-examples:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10"
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip
      - name: Install dependencies
        run: pnpm install
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Run test-examples script
        run: PYTHONUNBUFFERED=1 python examples/test-examples.py --skip-deploy
